# Workflow to build and test wheels
name: Wheel builder

on:
  push:
    branches:
      - master
      - CI

jobs:
  # Build the wheels for Linux, Windows and macOS for Python 3.8 and newer
  build_wheels:
    name: Build wheel for cp${{ matrix.python }}-${{ matrix.platform_id }}-${{ matrix.manylinux_image }}
    runs-on: ${{ matrix.os }}

    strategy:
      # Ensure that a wheel builder finishes even if another fails
      fail-fast: false
      matrix:
        include:
          - os: windows-latest
            python: 310
            bitness: 64
            platform_id: win_amd64

          - os: ubuntu-latest
            python: 310
            bitness: 64
            platform_id: manylinux_x_y

          - os: macos-latest
            bitness: 64
            python: 310
            platform_id: macosx_x86_64

          - os: macos-latest
            bitness: 64
            python: 310
            platform_id: macosx_arm64

    steps:
      - name: Checkout repo
        uses: actions/checkout@v1

      - name: Setup Python
        uses: actions/setup-python@v3
        with:
          python-version: '3.10'  # update once build dependencies are available

      - name: Build and test wheels
        run: |
          python -m pip install -U pip numpy
          python -m pip install twine build
          python -m build

      - name: Store artifacts
        uses: actions/upload-artifact@v2
        with:
          path: dist/*.whl
