# Workflow to build and test wheels
name: Wheel builder

on:
  push:
    branches:
      - master
      - CI

jobs:
  build_wheels:
    name: Build wheel for cp${{ matrix.python }}-${{ matrix.platform_id }}-${{ matrix.manylinux_image }}
    runs-on: ${{ matrix.os }}

    strategy:
      # Ensure that a wheel builder finishes even if another fails
      fail-fast: false
      matrix:
         os: [ubuntu-latest, macos-latest, windows-latest]

    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Setup Python
        uses: actions/setup-python@v3
        with:
          python-version: '3.10'  # update once build dependencies are available

      - name: Build and test wheels
        run: |
          python -m pip install -U pip numpy
          python -m pip install twine build
          python -m build

      - name: Store artifacts
        uses: actions/upload-artifact@v2
        with:
          path: dist/
  
  build_pypy_wheels:
    name: PyPy wheels on ${{ matrix.os }}
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-latest]

    steps:
    - uses: actions/checkout@v3

    - uses: pypa/cibuildwheel@2.7.0
      env:
        CIBW_BUILD: pp*

    - name: Show files
      run: ls -lh wheelhouse
      shell: bash

    - name: Upload wheels
      uses: actions/upload-artifact@v3
      with:
        path: dist/*.whl*.whl
